# Generated by Django 5.1.2 on 2024-10-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zssapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18, null=True),
        ),
    ]
