# Generated by Django 5.1.2 on 2024-10-31 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zssapi', '0003_alter_deposit_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='investment',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zssapi.network'),
        ),
    ]
